import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { StudentProvider } from "@/Context/StudentContext";

const monserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // <ContextProvider>
        <html lang="en">
            <StudentProvider>
                <body className={monserrat.className}>
                    {/* <Header /> */}
                    <main className="Main_">{children}</main>
                    {/* <Footer /> */}
                </body>
            </StudentProvider>
        </html>
        // </ContextProvider>
    );
}
